#!/bin/bash

# This script is run by .github/workflows/build.yml. Run it manually after
# changing command-line options, attack modes, or the module inventory.

set -euo pipefail

echo "If you're running this manually: make sure you have a fresh build; otherwise the wrong docs will be generated!"
echo " make clean && make -s"

echo "Start generate_docs.sh"

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
root_dir="$(cd -- "${script_dir}/../.." && pwd)"
hashcat_bin="${HASHCAT_BIN:-${root_dir}/hashcat}"
python_bin="${PYTHON_BIN:-python3}"

cd "${root_dir}"

# Run --help and save to docs/hashcat-help.md
echo 'These docs are automatically generated by GitHub Actions; see .github/workflows/build.yml. \' > docs/hashcat-help.md
echo 'All manual changes will be overwritten!' >> docs/hashcat-help.md
echo '```' >> docs/hashcat-help.md
"${hashcat_bin}" --help \
  | sed -E 's/^hashcat \(v[^)]*\) starting in help mode$/hashcat (shooter_hashcat) starting in help mode/' \
  >> docs/hashcat-help.md
echo '```' >> docs/hashcat-help.md

# Run --example-hashes and save to docs/hashcat-example-hashes.md
echo 'These docs are automatically generated by GitHub Actions; see .github/workflows/build.yml. \' > docs/hashcat-example-hashes.md
echo 'All manual changes will be overwritten!' >> docs/hashcat-example-hashes.md
echo '| Hash-mode | Hash-name | Kernels | Test | Example |' >> docs/hashcat-example-hashes.md
echo '|:-----------|:-----------|:-----------|:-----------|:---------------|' >> docs/hashcat-example-hashes.md
"${hashcat_bin}" --example-hashes --machine-readable --quiet | "${python_bin}" "${script_dir}/hashcat-example-hashes_machine-readable2md.py" >> docs/hashcat-example-hashes.md

echo "Done generate_docs.sh"
